In [1]:
import numpy as np
A = np.array([[0,1,1], [2,3,4], [4,2,-5]])

In [2]:
A

array([[ 0,  1,  1],
       [ 2,  3,  4],
       [ 4,  2, -5]])

In [3]:
p = 2
np.sum(abs(A)** p,axis=1) ** (1/p)

array([1.41421356, 5.38516481, 6.70820393])

In [4]:
np.power(np.sum(abs(A)** p,axis=1), 1/p) 

array([1.41421356, 5.38516481, 6.70820393])

In [5]:
np.max(abs(A),axis=1)

array([1, 4, 5])

In [6]:
A[A!=0]

array([ 1,  1,  2,  3,  4,  4,  2, -5])

In [7]:
np.sum(A!=0,axis=1)

array([2, 3, 3])

In [8]:
np.sort(np.power(np.sum(abs(A)** p,axis=1), 1/p))

array([1.41421356, 5.38516481, 6.70820393])

In [9]:
b = np.argsort(np.power(np.sum(abs(A)** p,axis=1), 1/p))
b

array([0, 1, 2], dtype=int64)

In [10]:
b[ : :-1]

array([2, 1, 0], dtype=int64)

In [11]:
A

array([[ 0,  1,  1],
       [ 2,  3,  4],
       [ 4,  2, -5]])

In [12]:
A[b[ : :-1]]

array([[ 4,  2, -5],
       [ 2,  3,  4],
       [ 0,  1,  1]])

## Ejercicio 3

In [16]:
a = np.array([15, 12, 14, 10, 1, 2, 1], dtype=np.int64)

In [17]:
indexes = np.unique(a, return_index=True)
indexes

(array([ 1,  2, 10, 12, 14, 15], dtype=int64),
 array([4, 5, 3, 1, 2, 0], dtype=int64))

In [18]:
id2idx = np.ones(indexes[0].max() + 1, dtype=np.int64) * -1

In [19]:
id2idx

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
      dtype=int64)

In [20]:
id2idx[indexes[0]] = indexes[1]

In [21]:
id2idx

array([-1,  4,  5, -1, -1, -1, -1, -1, -1, -1,  3, -1,  1, -1,  2,  0],
      dtype=int64)

In [22]:
id2idx[15]

0

In [23]:
indexes[0]

array([ 1,  2, 10, 12, 14, 15], dtype=int64)

In [24]:
indexes[1]

array([4, 5, 3, 1, 2, 0], dtype=int64)

In [25]:
a[0]

15

## ejercicio 4

In [225]:
truth =      np.array([1,1,0,1,1,1,0,0,0,1]) 
prediction = np.array([1,1,1,1,0,0,1,1,0,0])

In [228]:
TP = np.sum(truth * prediction)

In [229]:
TP

3

In [261]:
FP  = truth - prediction
FP

array([ 0,  0, -1,  0,  1,  1, -1, -1,  0,  1])

In [246]:
FP =  len(FP[FP==-1])
FP

3

In [247]:
precision = TP / (TP + FP)
precision

0.5

In [251]:
FN  = truth - prediction
FN = len(FN[FN==1])
FN

3

In [253]:
Recall = TP / (TP + FN)
Recall

0.5

In [254]:
TP_TN = truth - prediction
TP_TN = len(TP_TN[TP_TN==0])
TP_TN

4

In [255]:
Accuracy = TP_TN / (TP_TN + FP + FN)
Accuracy

0.4

In [257]:
from sklearn.metrics import classification_report


print(classification_report(truth,prediction))

## ejercicio 5

In [32]:
query_ids = np.array([1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4])
truth_relevance = np.array([1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [33]:
count_queries = np.bincount(query_ids)[1:]
count_queries

array([4, 3, 5, 4], dtype=int64)

In [28]:
true_relevance_mask = (truth_relevance == 1)
true_relevance_mask

array([ True, False,  True, False,  True,  True,  True, False, False,
       False, False, False,  True, False, False,  True])

In [29]:
np.bincount(query_ids[true_relevance_mask])

array([0, 2, 3, 0, 2], dtype=int64)

In [428]:
count_truth_relevance = np.bincount(query_ids[true_relevance_mask])[1:]
count_truth_relevance

array([2, 3, 0, 2], dtype=int64)

In [433]:
frac = sum(count_truth_relevance / count_queries)/ len(count_queries)
frac

0.5